### ISSUE TITLE
UEFA CL qualifying league position information

### ISSUE THREAD

**Issue by Saturn** [architv/soccer-cli#11]
I notice there is a desire to colour code UEFA CL spots and potentially EL spot too. This is just some simple information mainly about the currently supported leagues and their CL spot allocations.

The CL places would be simple enough because they are awarded purely on league position. ( Apart from the holders of both competitions )

* LLIGA: Liga BBVA (Spanish League) - **4 CL (3 Group Stage, 1 Play off)**
* BL: Bundesliga (German League) - **4 CL (3 Group Stage, 1 Play off)**
* EPL: English Premier League - **4 CL (3 Group Stage, 1 Play off)**
* SA: Serie A (Italian League) - **3 CL (2 Group Stage, 1 Play off)**
* PPL: Primeira Liga (Portuguese League) - **3 CL (2 Group Stage, 1 Play off)**
* FL: Ligue 1 (French League) - **3 CL (2 Group Stage, 1 3rd qualifying round)**
* DED: Eredivisie (Dutch League) - **2 CL (1 Group Stage, 1 3rd qualifying round)**

Europa League places will be trickier since it involves domestic cup winners and not just league position. But for the above leagues : The first place outside of a CL places gets placed into the group  stage of the EL. And then the next place is usually awarded a third round qualifying place. Although not in England for example where they have two domestic cups. And maybe France too.

**Comment by architv** [comment]
@Saturn Thanks for the information. As mentioned in #10 I will add the properties for CL qualifying spots and relegated teams. Europa league will be trickier though.

**Comment by architv** [comment]
@Saturn I've added properties CL qualifying spots and relegated teams

**Comment by Saturn** [comment]
Nice:exclamation:

**Comment by architv** [comment]
@Saturn How do you say I color code EL teams? Since England has two domestic cups, only team fifth position is guaranteed a spot. On the other hand in Spain teams at position fifth and sixth are both guaranteed a spot. So, should I color code only fifth position in case of EPL and fifth and sixth in case of La Liga?

**Comment by Saturn** [comment]
@architv That is possibly the best way to do it.

Seems like only England and France have one EL spot since they have two domestic cups.

And in the Eredivisie they have two spots. The 3 place team gets one. The other league spot is determined by a play off between the teams finishing 4th, 5th, 6th and 7th. Don't know how that could be represented :smile:
