### ISSUE TITLE
main.py refactoring

### ISSUE THREAD

**Issue by andyg7** [architv/soccer-cli#111]
Hey guys, 
I'm currently looking into writing tests for the app. I've finding some of the code slightly tough to test; I was thinking of refactoring main.py to be a little more object oriented, which I think would make it easier to test. Does this sound like something that would make sense to you guys?
Thanks!
Andy :)

**Comment by dfrt82** [comment]
Absolutely!

**Comment by carlosvargas** [comment]
I'm closing this since the PR has been merged.
