### ISSUE TITLE
League Standings shown are from previous season

### ISSUE THREAD

**Issue by phanikiranthaticharla** [architv/soccer-cli#121]
The league standings for any league shown are of previous season. 
It would be better if the standings shown would be of current season. 
Or there should be an option to select the year of the standings. 
![standings](https://user-images.githubusercontent.com/8190677/30942853-e216a20c-a3b2-11e7-8359-6fc019063000.PNG)

**Comment by dfrt82** [comment]
update your repo, i updated the league ids to the current season

**Comment by phanikiranthaticharla** [comment]
Thanks! Updated the repo and I am able to see the current standings. 
It would be better if there is an option to obtain the standings for a selected year too.
