### ISSUE TITLE
No standings available for --league.

### ISSUE THREAD

**Issue by RafaelBroseghini** [architv/soccer-cli#131]
I believe the soccer-cli is not retrieving any standings for leagues when invoking:
soccer --standings --league=LeagueName

![soccer](https://user-images.githubusercontent.com/26601054/36344290-983b6d52-13dd-11e8-94ed-d01dec691b04.PNG)

**Comment by gauravbg** [comment]
+1

**Comment by hmendozap** [comment]
One has to fix the request url. As of today (03.03) my understanding is that the API changed from alpha to v1 and soccerseasons to competitions. 

So in request_handler.py , line 9 should read:
````python
    BASE_URL = 'http://api.football-data.org/v1/'
````
and line 74:
````python
            req = self._get('competitions/{id}/leagueTable'.format(

````

and then follow instructions to install from source

**Comment by internetfan420** [comment]
still not getting standings with above fixes

**Comment by sebastiaanspeck** [comment]
The API has updated to V2. The urls has to be changed to V2

**Comment by Saturn** [comment]
This should work now.
