### ISSUE TITLE
QUESTION: error with imports

### ISSUE THREAD

**Issue by p-netm** [architv/soccer-cli#138]
am trying to run the program as a script i.e. assuming am inside the soccer-cli as my working directory
> python soccer/main.py

i keep getting the error shown below, i have not modified anything in the projects file structure
```sh
(venv) C:\Users\Sudo Pnet\Desktop\pyworks\soccer-cli>python soccer/main.py
Traceback (most recent call last):
  File "soccer/main.py", line 7, in <module>
    from soccer import leagueids
ImportError: No module named 'soccer'
```
Tried playing around with relative imports but that failed too. Am stumped someone help.

**Comment by Saturn** [comment]
You may have figured this out already. For anyone else try:

`python -m soccer.main`
