### ISSUE TITLE
error: file 'authtoken.py' does not exist

### ISSUE THREAD

**Issue by inter1965** [architv/soccer-cli#15]
running build
running build_scripts
error: file 'authtoken.py' does not exist

**Comment by alexpacurar** [comment]
Hi,

I got the same error when running **python setup.py install**, and to resolve it I created the file **authtoken.py** with the following contents:

###API_TOKEN='my_token'

**my_token** was obtained from [here](http://api.football-data.org/register)

**Comment by Saturn** [comment]
This info was added to the README 4b028415bd1ac092c5324a962ca422b348e452c1
