### ISSUE TITLE
[Help] Retrieving lineups on matches request

### ISSUE THREAD

**Issue by xascar** [architv/soccer-cli#155]
Does any body know why I'm not getting lineups when requesting a match by id even specifying header(A-Unfold-Lineups = true) as documentation says? Could it be due the free tier I'm using?

<img width="854" alt="image" src="https://user-images.githubusercontent.com/8994634/215837788-e287819e-3d76-409d-99b0-4a3d1dfa70c1.png">

**Comment by dfrt82** [comment]
n/a within free plan.
