### ISSUE TITLE
is that really necessary to put all the .py files under /usr/bin instead of /usr/lib/python2.7/site-packages/ ?

### ISSUE THREAD

**Issue by inter1965** [architv/soccer-cli#16]
soccer-cli /usr/
soccer-cli /usr/bin/
soccer-cli /usr/bin/authtoken.py
soccer-cli /usr/bin/leagueids.py
soccer-cli /usr/bin/liveapi.py
soccer-cli /usr/bin/main.py
soccer-cli /usr/bin/soccer
soccer-cli /usr/bin/teamnames.py
soccer-cli /usr/lib/
soccer-cli /usr/lib/python2.7/
soccer-cli /usr/lib/python2.7/site-packages/
soccer-cli /usr/lib/python2.7/site-packages/soccer_cli-0.0.3.1-py2.7.egg-info/
soccer-cli /usr/lib/python2.7/site-packages/soccer_cli-0.0.3.1-py2.7.egg-info/PKG-INFO
soccer-cli /usr/lib/python2.7/site-packages/soccer_cli-0.0.3.1-py2.7.egg-info/SOURCES.txt
soccer-cli /usr/lib/python2.7/site-packages/soccer_cli-0.0.3.1-py2.7.egg-info/dependency_links.txt
soccer-cli /usr/lib/python2.7/site-packages/soccer_cli-0.0.3.1-py2.7.egg-info/entry_points.txt
soccer-cli /usr/lib/python2.7/site-packages/soccer_cli-0.0.3.1-py2.7.egg-info/requires.txt
soccer-cli /usr/lib/python2.7/site-packages/soccer_cli-0.0.3.1-py2.7.egg-info/top_level.txt

**Comment by thurask** [comment]
I believe this is something to do with packaging, no?

Refactoring the repo to separate utility code and terminal commands might fix that, since only the scripts marked as terminal commands in setup.py would end up in /usr/bin, I think.

**Comment by Saturn** [comment]
Seems like only `soccer` should be in the `/usr/bin` folder.

This would be an important fix.
