### ISSUE TITLE
CSV/JSON output

### ISSUE THREAD

**Issue by inodb** [architv/soccer-cli#25]
Cool work! Is it possible to get the output in csv or json as well?

**Comment by Saturn** [comment]
I am sure it would be easy enough to add a flag that outputs to JSON / CSV instead of just printing to console.

**Comment by ueg1990** [comment]
done! can be closed now :)

**Comment by architv** [comment]
Implemented with #36

**Comment by inodb** [comment]
Sweet! Thanks!
