### ISSUE TITLE
CL playoff color spot

### ISSUE THREAD

**Issue by ueg1990** [architv/soccer-cli#34]
Hey now that we got EL spot, we should do a separate shade for the fourth spot :stuck_out_tongue: 

like here: http://www.espnfc.com/barclays-premier-league/23/table

**Comment by architv** [comment]
Currently the top four spots and green and bold. Would making the fourth spot (or the playoff spot) only green and bold do it?

**Comment by ueg1990** [comment]
looks good to me. 
@Saturn ?

**Comment by architv** [comment]
@Saturn @carlosvargas  any suggestions?

**Comment by Saturn** [comment]
Would there have to be slightly more detailed properties?

So we can differentiate group stage teams and 3rd round qualifying etc. It is kind of messy right now with how it checks the league properties and applies the correct colours.

**Comment by ueg1990** [comment]
its not a big deal now...we can close it for now and deal with it later or we can wait till one of us comes with a better solution. Most probably we will still have to update leagueproperties.py and update the lists again. If we end up doing that, we should definitely then introduce namedtuples for easier access

**Comment by architv** [comment]
Closing this for now.
