### ISSUE TITLE
Soccer CLI argument team not working

### ISSUE THREAD

**Issue by ueg1990** [architv/soccer-cli#37]
I ran the following command:

soccer --team=CRY (which i am assuming is Crystal Palace)

 but I get the following message:
'No action during past week. Change the time parameter to get more fixtures.'

Any specific reason this is happening? Crystal Palace played today in the morning

Also, what is the code for Chelsea?

**Comment by architv** [comment]
Ah! That is because the API is usually updated 12 hours after the game. 

The team code for Chelsea is `CFC`. [Here](teamcodes.json) is the list of all team codes.

**Comment by ueg1990** [comment]
Thanks :)
