### ISSUE TITLE
Remove shebang from main.py?

### ISSUE THREAD

**Issue by ueg1990** [architv/soccer-cli#44]
Hello,

I wanted to know if the line in main.py is needed:

#!/usr/bin/env python

Since its a command line project, i do not think you even need the shebang there.

**Comment by architv** [comment]
Well it's not really needed. I got there because I took some boilerplate from another of my code which had this.

**Comment by architv** [comment]
Fixed with ac2a6fbf3dd360b44347105e0db4855e0754ad6e
