### ISSUE TITLE
Spanish Standings are misaligned

### ISSUE THREAD

**Issue by gonch** [architv/soccer-cli#5]
<img width="472" alt="screen shot 2015-09-02 at 6 24 13 pm" src="https://cloud.githubusercontent.com/assets/827234/9637227/e2bfcb96-519f-11e5-8af5-17b4ef0be210.png">

It looks like this happens in rows with a non ascii character (Club Atl**é**tico de Madrid)

**Comment by agony** [comment]
German Bundesliga too.

**Comment by architv** [comment]
@gonch Right, this happens in rows with non ascii character. Therefore it happens in all the league with standings with team names containing non ascii character. Will fix this.
