### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by claudioruiz** [architv/soccer-cli#53]
Using OSX El Capitan here. 
After being successfully installed, each command I want to apply shows up this error:

```
~> soccer --help
Traceback (most recent call last):
  File "/usr/local/bin/soccer", line 7, in <module>
    from soccer.main import main
  File "/usr/local/lib/python2.7/site-packages/soccer/main.py", line 21, in <module>
    from config import config
ImportError: No module named config`
```
Thanks!

**Comment by architv** [comment]
Hi @claudioruiz,

I somehow missed out on a couple of instructions for installing from pip. 

So after installing, you'll need to get your API key from [here](http://api.football-data.org/register).

Then set the environment variable `SOCCER_CLI_API_TOKEN` to the key:

```
export SOCCER_CLI_API_TOKEN="<YOUR_API_TOKEN>"
```

This should fix your problem. I've also updated the [instructions](https://github.com/architv/soccer-cli#using-pip) in the README.

**Comment by claudioruiz** [comment]
Thanks!
