### ISSUE TITLE
Players option not available in pip package

### ISSUE THREAD

**Issue by prasadchelsea33** [architv/soccer-cli#55]
soccer --team=JUVE --players 
Added by @Ale46 at [Added players switch to get info about team players](https://github.com/architv/soccer-cli/pull/48) is not working when I installed using pip.

**Comment by Saturn** [comment]
I don't think the package on PyPi has been updated in a long time. I am not sure why that is.

The latest version here has a lot of issues though too.

**Comment by architv** [comment]
@Saturn Yes, I haven't updated the pypi version for some while. I am really sorry for ignoring `soccer-cli`.  Let's fix the errors in the latest version here, then I'll update it.

**Comment by architv** [comment]
@prasadchelsea33 @Saturn Added with the latest release. Please check this: https://github.com/architv/soccer-cli/releases/tag/0.0.1.0
