### ISSUE TITLE
Import the live API to version control

### ISSUE THREAD

**Issue by ctlaltdefeat** [architv/soccer-cli#6]
Instead of

```LIVE_API = 'http://soccer-cli.appspot.com/'```

have the actual code

**Comment by architv** [comment]
Sorry, I didn't get you. Could you please tell a bit more?

**Comment by Saturn** [comment]
Probably means have the code running `http://soccer-cli.appspot.com/` included. Presumably it uses some scraping or some other resource to get the live score data?

**Comment by architv** [comment]
Yes, I built that resource to scrape live scores. Since, it is not part of the business logic of the application, I separated it out. Is it anyway better to include that code here?

**Comment by ueg1990** [comment]
I think you should have it in your main.py like you did with the following:
BASE_URL = 'http://api.football-data.org/alpha/'

**Comment by ctlaltdefeat** [comment]
Sorry, I did in fact mean to have the code running the live API included

**Comment by architv** [comment]
I am not sure if that is necessary. If need be I'll make separate repo an push that code here.
