### ISSUE TITLE
Adding new collaborators

### ISSUE THREAD

**Issue by architv** [architv/soccer-cli#62]
Soccer CLI has come a long way from where it started. The current version has lot many more features than the one I originally created. I am grateful for all the love and the strong support shown by the open source community.

 Lately, I have got busy working with other projects and college, which has resulted in me ignoring `soccer-cli`. I have realised that for `soccer-cli` to be continuously made better, I would need help from people in the community. Thus I am adding new collaborators to `soccer-cli`.

I am adding @Saturn and @ueg1990 as collaborators for their amazing contribution to Soccer CLI!

**PS**: @ueg1990 and @Saturn please let me know if you have any issues with this.

**Comment by ueg1990** [comment]
thank you @architv :)

**Comment by Saturn** [comment]
Thanks @architv 

I imagine we will have to submit pull requests and get them looked over by someone. I wouldn't want to be solely responsible for pushing some awful changes :sweat_smile:

**Comment by architv** [comment]
@Saturn We can look over each other's PRs :smiley:
