### ISSUE TITLE
Releasing Soccer CLI 0.1

### ISSUE THREAD

**Issue by architv** [architv/soccer-cli#67]
I have updated the pypi version of soccer-cli to the latest version here. Please read the release notes here: https://github.com/architv/soccer-cli/wiki/Release-Notes-for-0.1

Also, I felt that there is no good way to communicate about project here so would it be better if we had another communication channel like gitter, slack or a google group (or anything else)?

cc: @Saturn @ueg1990 @carlosvargas

**Comment by Saturn** [comment]
Sounds like a good idea to me. It would be nice to coordinate on any work in progress we might have.

**Comment by carlosvargas** [comment]
Same here, I'm in for more communication between us.

**Comment by architv** [comment]
@Saturn @carlosvargas Okay! I've setup a gitter chat room and I've sent out the invites to you guys.
Link for the room: https://gitter.im/architv/soccer-cli?utm_source=share-link&utm_medium=link&utm_campaign=share-link
