### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by carlostkd** [architv/soccer-cli#72]
afther doing all i got this fail:

carlostkd@adsb-server:~> soccer --standings --league=EPL
No standings availble for EPL.
carlostkd@adsb-server:~> 

carlostkd@adsb-server:~> soocer --team=MUFC
If 'soocer' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf soocer
carlostkd@adsb-server:~> 

carlostkd@adsb-server:~> soccer --standings --league=PPL
No standings availble for PPL.
carlostkd@adsb-server:~> 

what is wrong???

**Comment by thurask** [comment]
Latest version, I assume?

And is your API key set up?

**Comment by carlostkd** [comment]
yes latest version and yes api key is setting up in config.py

**Comment by architv** [comment]
Hi @carlostkd , 
I am not able to reproduce the error. Could you clone the latest version here and try again?

**Comment by carlostkd** [comment]
HI @architv  i have uninstalled soccer-cli , i have removed the soccer-cli directory and when i try to clone again this is whats happen to me:

carlostkd@adsb-server:~> sudo git clone git@github.com:architv/soccer-cli.git
Cloning into 'soccer-cli'...
The authenticity of host 'github.com (192.30.252.120)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48 [MD5].
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.120' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
carlostkd@adsb-server:~> cd soccer-cli
bash: cd: soccer-cli: No such file or directory
carlostkd@adsb-server:~>

**Comment by thurask** [comment]
What about just:

```
$ git clone http://github.com/architv/soccer-cli.git
```

?

**Comment by carlostkd** [comment]
@thurask  well almost done.....

carlostkd@adsb-server:~> git clone http://github.com/architv/soccer-cli.git
Cloning into 'soccer-cli'...
remote: Counting objects: 720, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 720 (delta 27), reused 0 (delta 0), pack-reused 674
Receiving objects: 100% (720/720), 136.19 KiB | 0 bytes/s, done.
Resolving deltas: 100% (447/447), done.
Checking connectivity... done.
carlostkd@adsb-server:~> cd soccer-cli
carlostkd@adsb-server:~/soccer-cli> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
carlostkd@adsb-server:~/soccer-cli>

**Comment by thurask** [comment]
```
$ pip install setuptools
```
?

**Comment by ueg1990** [comment]
@carlostkd if you are cloning for the sake of development, I highly recommend cloning within a virtual environment...in that way you will not have to worry about dependencies and versions of other libraries :smile: 

Please let us know if you need help :smile:

**Comment by carlostkd** [comment]
@thurask   not works.....

carlostkd@adsb-server:~/soccer-cli> sudo pip install --upgrade setuptools
root's password:
Collecting setuptools
  Downloading setuptools-20.7.0-py2.py3-none-any.whl (508kB)
    100% |████████████████████████████████| 512kB 666kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 18.3.2
    Uninstalling setuptools-18.3.2:
      Successfully uninstalled setuptools-18.3.2
Successfully installed setuptools-20.7.0
carlostkd@adsb-server:~/soccer-cli> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
carlostkd@adsb-server:~/soccer-cli>

**Comment by carlostkd** [comment]
@ueg1990 hi thanks for the help , but unfortunatly you are talking in chinese for me ....

**Comment by ueg1990** [comment]
lol nice! i would highly recommend putting sometime understanding and using virtual environments with Python projects...its is worth it! :smile: 
http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by carlostkd** [comment]
@ueg1990 thanks bro i have added to favorits maybe be usefull for another think, but for a simple soccer-cli its to much job ah ah , thanks anyway

**Comment by ueg1990** [comment]
sounds good! getting back to your original issue...open a python console and verify if you can actually import setuptools

**Comment by carlostkd** [comment]
@ueg1990 sounds really good and maybe there is a code for doing that.... can you share please? i am basis in linux and dont know much about pyhton.
thanks in advance

**Comment by ueg1990** [comment]
run the command 'python' in your linux terminal and then do 'import setuptools':

-bash-4.1$ python
Python 2.6.6 (r266:84292, Jan 22 2014, 01:49:05)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>>

**Comment by carlostkd** [comment]
thanks to all for the help i have do that 

sudo apt-get install python-setuptools

afther that i can run setup.py install without problems and now all works fine

carlostkd@adsb-server:~> soccer --standings --league=EPL
POS     CLUB                              PLAYED        GOAL DIFF     POINTS    
1       Leicester City FC                 33            26            72
2       Tottenham Hotspur FC              33            35            65
3       Arsenal FC                        32            22            59
4       Manchester City FC                32            25            57
5       Manchester United FC              32            9             53
6       West Ham United FC                32            12            52
7       Southampton FC                    33            10            50
8       Liverpool FC                      31            8             48
9       Stoke City FC                     33           -6             47
10      Chelsea FC                        32            7             44
11      AFC Bournemouth                   33           -15            41
12      Swansea City FC                   33           -8             40
13      West Bromwich Albion FC           32           -8             40
14      Everton FC                        31            9             39
15      Watford FC                        32           -6             38
16      Crystal Palace FC                 32           -7             37
17      Norwich City FC                   33           -22            31
18      Sunderland AFC                    32           -21            27
19      Newcastle United FC               32           -29            25
20      Aston Villa FC                    33           -41            16
carlostkd@adsb-server:~>

**Comment by ueg1990** [comment]
:+1: thats awesome! :smile:

**Comment by architv** [comment]
Great @ueg1990 @thurask !
