### ISSUE TITLE
Premier League Table Bug

### ISSUE THREAD

**Issue by SolomonBier** [architv/soccer-cli#76]
Searching for the current Premier League table shows Leicester City 7 points clear at the top.

This cannot possibly b....

oh wait :/

**Comment by Sohil876** [comment]
They are 7 points clear: http://premierleague.com/en-gb/league-table.html

**Comment by timclifford** [comment]
Lol only 6 games left... Who knows

**Comment by SolomonBier** [comment]
COYS !!!!
