### ISSUE TITLE
# Feature request

### ISSUE THREAD

**Issue by AjithPanneerselvam** [architv/soccer-cli#85]
It's really a great effort to bring the football scores, stats and others in command line interface. I'm happy with soccer-cli.

Following is just the enhancement that I feel in user perspective.
- As we are using abbreviated form for the team name, league name.It is plausible that the user may not have idea about the abbreviation. So, it would be better to trigger suggestion if the user goes partially wrong.

eg: If the user intend to see the status of European Premier League(EPL), and the command he has given is like "soccer  --league=EFL", it would be good to give all possible suggestion.

**Comment by Saturn** [comment]
If the user types an incorrect league code they will be given a list of possible correct values. Although it is not as descriptive as I would like.

When you do `soccer --help` you get a list of league codes with corresponding league names which is more helpful.
