### ISSUE TITLE
Not returning any data

### ISSUE THREAD

**Issue by gauravmokhasi** [architv/soccer-cli#90]
$>soccer --standings --league=EPL
No standings availble for EPL.

$>soccer --team=MUFC --players
No data for the team. Please check the team code.

$>soccer --team=JUVE --players
No data for the team. Please check the team code.

$>soccer --league=EPL --time=20
No data for the given league.

$>soccer --league=CL
No data for the given league.

$>soccer --standings --league=CL
No standings availble for CL.

---

Environment: Windows

**Comment by carlosvargas** [comment]
Did you clone from Github or use PIP? PIP it's currently outdated, I pinged Archit to update the package, but in the mean time Github will have the latest changes.
