### ISSUE TITLE
term soccer not recognised. [Windows-cmd]

### ISSUE THREAD

**Issue by AadeshAKulkarni** [architv/soccer-cli#97]
@architv @rodrigoflores @Ale46  
I'm new to this.
I installed everything. and set the env variable as mentioned. 
opened windows PS and in the master directory typed this cmd: 
**$ soccer --standings --league=EPL**

and got the following error. Can someone help?

soccer : The term 'soccer' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ soccer --standings --league=EPL
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (soccer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by carlosvargas** [comment]
What's the output of `pip show soccer-cli`?

**Comment by AadeshAKulkarni** [comment]
C:\Users\Dell\Desktop>pip show soccer-cli
---
Metadata-Version: 1.1
Name: soccer-cli
Version: 0.1.0.0
Summary: Soccer for Hackers.
Home-page: https://github.com/architv/soccer-cli
Author: Archit Verma
Author-email: architv07@gmail.com
License: MIT
Location: c:\python27\lib\site-packages\soccer_cli-0.1.0.0-py2.7.egg
Requires: click, requests, colorama
Classifiers:
  Development Status :: 3 - Alpha
  Intended Audience :: Developers
  Topic :: Software Development :: Build Tools
  License :: OSI Approved :: MIT License
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
Entry-points:
  [console_scripts]
  soccer = soccer.main:main

**Comment by AadeshAKulkarni** [comment]
@carlosvargas  I hadnt installed pip before. I installed it after your comment and now everything's working fine. Thanks a lot,man!

**Comment by carlosvargas** [comment]
Sorry if I mislead you into installing the pip version, I thought you already had that installed. We're recommending the git checkout since the pip version is outdated and some of the stuff might not work properly. 

To run the github clone, what I do is just cd to the root directory of the checkout and run it using `python -m soccer.main`

**Comment by sokravtsov** [comment]
Hello,

I use macOS Sierra 10.12.5 after I installed by pip, and try call 
`soccer --help`
bash output:
`-bash: soccer: command not found`

my $PATH /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/‌​bin/
