### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by andyg7** [architv/soccer-cli#99]
Hi!
I was hoping to contribute to this project. It seems like there currently aren't any tests (unit tests specifically), so I was thinking that could be a good way to get involved? If so, are there any guidelines for what kind of testing suite you guys would want setup? I saw test.py in the tests directory and it imports unittest so I assume that's the testing tool to use, but wanted to see if there is anything else to keep in mind or know before I got started.
Thanks for any advice :) 
Andrew

**Comment by ueg1990** [comment]
Hey @andyg7 sorry for the late reply. Tests would be great. There are many options. For unit tests you can use unittest library. You can also write integrate tests for functions/methods that interact with a HTTP API; for that I would recommend using the requests_mock library as it makes it really easy to mock the APIs and make the code readable. If you are still interested in working on this task, I can help you get started :)

**Comment by andyg7** [comment]
hey @ueg1990 sorry for the late response myself. I'd definitely like to still contribute if possible. I've looked through the code before but will do again. I've used unittest before so would be happy to use that tool for sure. 
Let me know if there's anything to keep in mind and obviously any advice on the best way to get going would be much appreciated :)

**Comment by andyg7** [comment]
Hey @ueg1990 
I was going to start looking into writing some tests. Let me know if there's anything you guys are looking for!
Thanks again :)
